// https://nuxt.com/docs/api/configuration/nuxt-config

export default defineNuxtConfig({
  compatibilityDate: '2025-07-15',
  devtools: { enabled: true },
  modules: ['@nuxtjs/tailwindcss'],
  typescript: {
    strict: true,
  },
  nitro: {
    preset: 'vercel',
    serverAssets: [
      { baseName: 'certs', dir: './certs' },
      { baseName: 'fonts', dir: './fonts' },
    ],
    // Prisma must stay external: bundling into ESM breaks __dirname in the query engine.
    // traceInclude copies .prisma/client binaries into the Vercel function output.
    externals: {
      traceInclude: [
        'node_modules/.prisma/client/**',
        'node_modules/@prisma/client/**',
      ],
      inline: [
        '@vue/server-renderer',
        '@vue/compiler-dom',
        '@vue/runtime-dom',
        '@vue/shared',
        '@vue/runtime-core',
        '@vue/compiler-core',
        '@vue/compiler-ssr',
        '@vue/reactivity',
        'vue',
        'vue-bundle-renderer',
        'vue-router',
        'unhead',
        'devalue',
        'hookable',
        'entities',
        'estree-walker',
        'source-map-js',
      ],
    },
  },
  runtimeConfig: {
    databaseUrl: process.env.DATABASE_URL,
    blobStoreId: process.env.BLOB_STORE_ID,
    blobWebhookPublicKey: process.env.BLOB_WEBHOOK_PUBLIC_KEY,
    telegramBotToken: process.env.TELEGRAM_BOT_TOKEN,
    telegramBotUsername: process.env.TELEGRAM_BOT_USERNAME ?? '',
    maxBotToken: process.env.MAX_BOT_TOKEN,
    maxBotLink: process.env.MAX_BOT_LINK ?? '',
    maxBotUsername: process.env.MAX_BOT_USERNAME ?? '',
    maxWebhookSecret: process.env.MAX_WEBHOOK_SECRET,
    adminSecret: process.env.ADMIN_SECRET,
    agentApiKey: process.env.AGENT_API_KEY,
    pricePerPageKopeks: process.env.PRICE_PER_PAGE_KOPEKS ?? '1000',
    calculationTimeoutSec: process.env.CALCULATION_TIMEOUT_SEC ?? '300',
    paymentMode: process.env.PAYMENT_MODE ?? 'terminal',
    pointTransferPhone: process.env.POINT_TRANSFER_PHONE ?? '',
    pointTransferBankLabel: process.env.POINT_TRANSFER_BANK_LABEL ?? '',
    paymentMethodsEnabled: process.env.PAYMENT_METHODS_ENABLED ?? 'SBP_TRANSFER,ON_SITE',
    staffTelegramChatId: process.env.STAFF_TELEGRAM_CHAT_ID ?? '',
    staffMaxUserId: process.env.STAFF_MAX_USER_ID ?? '',
    batchMaxFiles: process.env.BATCH_MAX_FILES ?? '5',
    batchBuildTimeoutMin: process.env.BATCH_BUILD_TIMEOUT_MIN ?? '15',
    pointOfflineThresholdSec: process.env.POINT_OFFLINE_THRESHOLD_SEC ?? '20',
    tbankTerminalKey: process.env.TBANK_TERMINAL_KEY ?? '',
    tbankPassword: process.env.TBANK_PASSWORD ?? '',
    tbankWebhookSecret: process.env.TBANK_WEBHOOK_SECRET ?? '',
    tbankApiUrl: process.env.TBANK_API_URL ?? 'https://securepay.tinkoff.ru/v2',
    tbankNotificationUrl: process.env.TBANK_NOTIFICATION_URL ?? '',
    tbankReceiptEnabled: process.env.TBANK_RECEIPT_ENABLED ?? 'false',
    tbankReceiptEmail: process.env.TBANK_RECEIPT_EMAIL ?? '',
    payoutPayerName: process.env.PAYOUT_PAYER_NAME ?? '',
    payoutPayerInn: process.env.PAYOUT_PAYER_INN ?? '',
    payoutPayerAccount: process.env.PAYOUT_PAYER_ACCOUNT ?? '',
    payoutPayerBik: process.env.PAYOUT_PAYER_BIK ?? '',
    payoutPayerBankName: process.env.PAYOUT_PAYER_BANK_NAME ?? '',
    payoutPayerCorrAccount: process.env.PAYOUT_PAYER_CORR_ACCOUNT ?? '',
    public: {
      appVersion: '0.0.1',
      siteUrl: process.env.NUXT_PUBLIC_SITE_URL ?? '',
      legalEntityName: process.env.NUXT_PUBLIC_LEGAL_ENTITY_NAME ?? '',
      legalInn: process.env.NUXT_PUBLIC_LEGAL_INN ?? '',
      legalOgrnip: process.env.NUXT_PUBLIC_LEGAL_OGRNIP ?? '',
      legalAddress: process.env.NUXT_PUBLIC_LEGAL_ADDRESS ?? '',
      legalEmail: process.env.NUXT_PUBLIC_LEGAL_EMAIL ?? '',
    },
  },
})
